package com.securitybox.editokenizerRest;
import com.securitybox.constants.*;
public class Constants {
    static final String requestTokenizerEDISample  ="UNA:+.? "+"’"+"UNB+UNOC:3+PartnerA+PartnerB+100615:0100+1006150100000++MYCOMPANY'UNH+1+IFTMIN:S:93A:UN'BGM+340+0000001339+9'DTM+137:20100615:102'TSR+PCO'FTX+DIN+++Delivery information'CNT+7:7.000:KGM'CNT+26:0.500:MTQ'CNT+ZLM:0.40:MTR'CNT+Z12:3:PCE'CNT+11:3:PCE'RFF+AAO:Receivers reference'RFF+CU:Shipment reference'TDT+20'NAD+CZ+123456++MYCOMPANY AB+Box 2326 +GEBORG++40315+SE'CTA+IC+:John Doe'COM+031-581600:TE'COM+031-7581605:FX'COM+info@MYCOMPANY.com:EM'NAD+CN+++Testmottagaren AB+Sdervsvn 12 +VTRA FRUNDA++42651+SE'CTA+IC+:Bjrn Svensson'COM+012-3456789:TE'COM+012-9876543:FX'COM+test@test.com:EM'COM+07353289222:ZMS'GID+1+1:CT'FTX+AAA+++Electronics'FTX+PAC+++9'MEA+WT++KGM:5.000'MEA+VOL++MTQ:0.300'PCI+18+373925550000420599'GID+2+2:CT'FTX+AAA+++Electronics'FTX+PAC+++9'MEA+WT++KGM:2.000'MEA+VOL++MTQ:0.200'PCI+18+373925550000420605:373925550000420612'EQD+EFP'EQN+1'UNT+39+1'UNZ+1+1006150100000'"; static final String requestDeTokenizerEDISample="Please refere to the response from tokenization API call.";
    static final String elementsToTokenizeJsonEDIFACT ="[{\""
            + com.securitybox.constants.Constants.EDIFACT_SEGMENT_NAME + "\":\"NAD\",\"" + com.securitybox.constants.Constants.EDIFACT_SEGMENT_QUALIFIER   + "\":\"CN\",\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_NUMBER + "\":5,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_POSITION + "\":1,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_LENGTH + "\":30},{\""
            + com.securitybox.constants.Constants.EDIFACT_SEGMENT_NAME + "\":\"NAD\",\"" + com.securitybox.constants.Constants.EDIFACT_SEGMENT_QUALIFIER   + "\":\"CN\",\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_NUMBER + "\":6,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_POSITION + "\":1,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_LENGTH + "\":30},{\""
            + com.securitybox.constants.Constants.EDIFACT_SEGMENT_NAME + "\":\"NAD\",\"" + com.securitybox.constants.Constants.EDIFACT_SEGMENT_QUALIFIER   + "\":\"CN\",\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_NUMBER + "\":7,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_POSITION + "\":1,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_LENGTH + "\":30},{\""
            + com.securitybox.constants.Constants.EDIFACT_SEGMENT_NAME + "\":\"CTA\",\"" + com.securitybox.constants.Constants.EDIFACT_SEGMENT_QUALIFIER   + "\":\"IC\",\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_NUMBER + "\":3,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_POSITION + "\":2,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_LENGTH + "\":30},{\""
            + com.securitybox.constants.Constants.EDIFACT_SEGMENT_NAME + "\":\"RFF\",\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_NUMBER + "\":2,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_POSITION + "\":2,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_LENGTH + "\":30},{\""
            + com.securitybox.constants.Constants.EDIFACT_SEGMENT_NAME + "\":\"COM\",\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_NUMBER + "\":3,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_POSITION + "\":2,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_LENGTH + "\":20}]";
    static final String elementsToDeTokenizeJsonEDIFACT ="[{\""
            + com.securitybox.constants.Constants.EDIFACT_SEGMENT_NAME + "\":\"NAD\",\"" + com.securitybox.constants.Constants.EDIFACT_SEGMENT_QUALIFIER   + "\":\"CN\",\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_NUMBER + "\":5,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_POSITION + "\":1},{\""
            + com.securitybox.constants.Constants.EDIFACT_SEGMENT_NAME + "\":\"NAD\",\"" + com.securitybox.constants.Constants.EDIFACT_SEGMENT_QUALIFIER   + "\":\"CN\",\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_NUMBER + "\":6,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_POSITION + "\":1},{\""
            + com.securitybox.constants.Constants.EDIFACT_SEGMENT_NAME + "\":\"NAD\",\"" + com.securitybox.constants.Constants.EDIFACT_SEGMENT_QUALIFIER   + "\":\"CN\",\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_NUMBER + "\":7,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_POSITION + "\":1},{\""
            + com.securitybox.constants.Constants.EDIFACT_SEGMENT_NAME + "\":\"CTA\",\"" + com.securitybox.constants.Constants.EDIFACT_SEGMENT_QUALIFIER   + "\":\"IC\",\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_NUMBER + "\":3,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_POSITION + "\":2},{\""
            + com.securitybox.constants.Constants.EDIFACT_SEGMENT_NAME + "\":\"RFF\",\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_NUMBER + "\":2,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_POSITION + "\":2},{\""
            + com.securitybox.constants.Constants.EDIFACT_SEGMENT_NAME + "\":\"COM\",\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_NUMBER + "\":2,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_POSITION + "\":1}]";

    static final String requestTokenizerCSVSample  ="Raw1_column_1_data:Raw1_column_2_data:Raw1_column_3_data:Raw1_column_4_data\nRaw2_column_1_data:Raw2_column_2_data:Raw2_column_3_data:Raw2_column_4_data";
    static final String requestDeTokenizerCSVSample  ="Raw1_column_1_data:Raw1_column_2_data:Raw1_column_3_data:Raw1_column_4_data\nRaw2_column_1_data:Raw2_column_2_data:Raw2_column_3_data:Raw2_column_4_data";
    static final String elementsToTokenizeJsonCSV ="[{\""
            + com.securitybox.constants.Constants.CSV_DATA_ELEMENT_POSITION + "\":1,\"" + com.securitybox.constants.Constants.CSV_DATA_ELEMENT_LENGTH + "\":30},{\""
            + com.securitybox.constants.Constants.CSV_DATA_ELEMENT_POSITION + "\":2,\"" + com.securitybox.constants.Constants.CSV_DATA_ELEMENT_LENGTH + "\":20}]";
    static final String elementsToDeTokenizeJsonExampleCSV="[{\""
            + com.securitybox.constants.Constants.CSV_DATA_ELEMENT_POSITION + "\":1},{\"" + com.securitybox.constants.Constants.CSV_DATA_ELEMENT_POSITION + "\":2}]";

}
