package com.securitybox.editokenizerRest;
import com.securitybox.constants.*;
public class Constants {
    static final String requestTokenizerEDISample  ="UNA:+. ?'UNB+UNOC:3+SENDERID+RECIPIENTID+100615:0100+1006150100000++MYCOMPANY'UNH+1+IFTMIN:S:93A:UN'BGM+340+0000001339+9'DTM+137:20100615:102'TSR+PCO'RFF+AAO:Receivers reference'RFF+CU:Shipment reference'TDT+20'NAD+CZ+123456++Sender AB+Box 2326 +GEBORG++40315+SE'CTA+IC+:John Doe'COM+031-581600:TE'COM+031-7581605:FX'COM+info@Sender.com:EM'NAD+CN+++Testmottagaren AB+Sdervsvn 12 +VTRA FRUNDA++42651+SE'CTA+IC+:Bjrn Svensson'UNT+XX+1'UNZ+1+1006150100000'";
    static final String requestDeTokenizerEDISample="UNA:+. ?'UNB+UNOC:3+SENDERID+RECIPIENTID+100615:0100+1006150100000++MYCOMPANY'UNH+1+IFTMIN:S:93A:UN'BGM+340+0000001339+9'DTM+137:20100615:102'TSR+PCO'RFF+AAO:Receivers reference'RFF+CU:Shipment reference'TDT+20'NAD+CZ+123456++Sender AB+Box 2326 +GEBORG++40315+SE'CTA+IC+:John Doe'COM+031-581600:TE'COM+031-7581605:FX'COM+info@Sender.com:EM'NAD+CN+++Testmottagaren AB+Sdervsvn 12 +VTRA FRUNDA++42651+SE'CTA+IC+:Bjrn Svensson'UNT+YY+1'UNZ+1+1006150100000'";
    static final String elementsToTokenizeJsonEDIFACT ="[{\""
            + com.securitybox.constants.Constants.EDIFACT_SEGMENT_NAME + "\":\"NAD\",\"" + com.securitybox.constants.Constants.EDIFACT_SEGMENT_QUALIFIER   + "\":\"CN\",\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_NUMBER + "\":5,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_POSITION + "\":1,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_LENGTH + "\":30},{\""
            + com.securitybox.constants.Constants.EDIFACT_SEGMENT_NAME + "\":\"RFF\",\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_NUMBER + "\":2,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_POSITION + "\":2,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_LENGTH + "\":30},{\""
            + com.securitybox.constants.Constants.EDIFACT_SEGMENT_NAME + "\":\"CTA\",\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_NUMBER + "\":3,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_POSITION + "\":2,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_LENGTH + "\":20}]";
    static final String elementsToDeTokenizeJsonEDIFACT ="[{\""
            + com.securitybox.constants.Constants.EDIFACT_SEGMENT_NAME + "\":\"NAD\",\"" + com.securitybox.constants.Constants.EDIFACT_SEGMENT_QUALIFIER   + "\":\"CN\",\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_NUMBER + "\":5,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_POSITION + "\":1},{\""
            + com.securitybox.constants.Constants.EDIFACT_SEGMENT_NAME + "\":\"RFF\",\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_NUMBER + "\":2,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_POSITION + "\":2},{\""
            + com.securitybox.constants.Constants.EDIFACT_SEGMENT_NAME + "\":\"CTA\",\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_NUMBER + "\":3,\"" + com.securitybox.constants.Constants.EDIFACT_DATA_ELEMENT_POSITION + "\":2}]";

    static final String requestTokenizerCSVSample  ="Raw1_column_1_data:Raw1_column_2_data:Raw1_column_3_data:Raw1_column_4_data\nRaw2_column_1_data:Raw2_column_2_data:Raw2_column_3_data:Raw2_column_4_data";
    static final String requestDeTokenizerCSVSample  ="Raw1_column_1_data:Raw1_column_2_data:Raw1_column_3_data:Raw1_column_4_data\nRaw2_column_1_data:Raw2_column_2_data:Raw2_column_3_data:Raw2_column_4_data";
    static final String elementsToTokenizeJsonCSV ="[{\"" + com.securitybox.constants.Constants.CSV_DATA_ELEMENT_POSITION + "\":1,\"" + com.securitybox.constants.Constants.CSV_DATA_ELEMENT_LENGTH + "\":30},{\"" + com.securitybox.constants.Constants.CSV_DATA_ELEMENT_POSITION + "\":2,\"" + com.securitybox.constants.Constants.CSV_DATA_ELEMENT_LENGTH + "\":20}]";
    static final String elementsToDeTokenizeJsonExampleCSV="[{\"" + com.securitybox.constants.Constants.CSV_DATA_ELEMENT_POSITION + "\":1,{\"" + com.securitybox.constants.Constants.CSV_DATA_ELEMENT_POSITION + "\":2]";

}
